/*
 * Candidates API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.smartrecruiters.api.candidates.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AnswerFieldValue
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-23T14:57:09.146594+01:00[Europe/London]")
public class AnswerFieldValue {
  @SerializedName("id")
  private String id = null;

  @SerializedName("label")
  private String label = null;

  public AnswerFieldValue id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Value text or value ID - depends on question definition
   * @return id
  **/
  @Schema(required = true, description = "Value text or value ID - depends on question definition")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AnswerFieldValue label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Value text shown to candidate
   * @return label
  **/
  @Schema(required = true, description = "Value text shown to candidate")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnswerFieldValue answerFieldValue = (AnswerFieldValue) o;
    return Objects.equals(this.id, answerFieldValue.id) &&
        Objects.equals(this.label, answerFieldValue.label);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnswerFieldValue {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
