/*
 * Candidates API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.smartrecruiters.api.candidates.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.candidates.model.AnswerFieldValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AnswerField
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-29T00:16:14.530797+01:00[Europe/London]")
public class AnswerField {
  @SerializedName("id")
  private String id = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("values")
  private List<AnswerFieldValue> values = new ArrayList<AnswerFieldValue>();

  public AnswerField id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AnswerField label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Field label shown to candidate - ignore when empty
   * @return label
  **/
  @Schema(description = "Field label shown to candidate - ignore when empty")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public AnswerField values(List<AnswerFieldValue> values) {
    this.values = values;
    return this;
  }

  public AnswerField addValuesItem(AnswerFieldValue valuesItem) {
    this.values.add(valuesItem);
    return this;
  }

   /**
   * Multiple values may be used for example for Multiselect Dropdown question
   * @return values
  **/
  @Schema(required = true, description = "Multiple values may be used for example for Multiselect Dropdown question")
  public List<AnswerFieldValue> getValues() {
    return values;
  }

  public void setValues(List<AnswerFieldValue> values) {
    this.values = values;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnswerField answerField = (AnswerField) o;
    return Objects.equals(this.id, answerField.id) &&
        Objects.equals(this.label, answerField.label) &&
        Objects.equals(this.values, answerField.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, values);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnswerField {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
