/*
 * Candidates API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.smartrecruiters.api.candidates.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CandidateSource
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-29T00:16:14.530797+01:00[Europe/London]")
public class CandidateSource {
  @SerializedName("sourceTypeId")
  private String sourceTypeId = null;

  @SerializedName("sourceSubTypeId")
  private String sourceSubTypeId = null;

  @SerializedName("sourceId")
  private String sourceId = null;

  public CandidateSource sourceTypeId(String sourceTypeId) {
    this.sourceTypeId = sourceTypeId;
    return this;
  }

   /**
   * Get sourceTypeId
   * @return sourceTypeId
  **/
  @Schema(required = true, description = "")
  public String getSourceTypeId() {
    return sourceTypeId;
  }

  public void setSourceTypeId(String sourceTypeId) {
    this.sourceTypeId = sourceTypeId;
  }

  public CandidateSource sourceSubTypeId(String sourceSubTypeId) {
    this.sourceSubTypeId = sourceSubTypeId;
    return this;
  }

   /**
   * Get sourceSubTypeId
   * @return sourceSubTypeId
  **/
  @Schema(description = "")
  public String getSourceSubTypeId() {
    return sourceSubTypeId;
  }

  public void setSourceSubTypeId(String sourceSubTypeId) {
    this.sourceSubTypeId = sourceSubTypeId;
  }

  public CandidateSource sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Get sourceId
   * @return sourceId
  **/
  @Schema(required = true, description = "")
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidateSource candidateSource = (CandidateSource) o;
    return Objects.equals(this.sourceTypeId, candidateSource.sourceTypeId) &&
        Objects.equals(this.sourceSubTypeId, candidateSource.sourceSubTypeId) &&
        Objects.equals(this.sourceId, candidateSource.sourceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceTypeId, sourceSubTypeId, sourceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidateSource {\n");
    
    sb.append("    sourceTypeId: ").append(toIndentedString(sourceTypeId)).append("\n");
    sb.append("    sourceSubTypeId: ").append(toIndentedString(sourceSubTypeId)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
