/*
 * Candidates API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.smartrecruiters.api.candidates.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.candidates.model.Action;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CandidateDetailsActions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-23T14:57:09.146594+01:00[Europe/London]")
public class CandidateDetailsActions {
  @SerializedName("properties")
  private Action properties = null;

  @SerializedName("attachments")
  private Action attachments = null;

  @SerializedName("consent")
  private Action consent = null;

  public CandidateDetailsActions properties(Action properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @Schema(required = true, description = "")
  public Action getProperties() {
    return properties;
  }

  public void setProperties(Action properties) {
    this.properties = properties;
  }

  public CandidateDetailsActions attachments(Action attachments) {
    this.attachments = attachments;
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  @Schema(description = "")
  public Action getAttachments() {
    return attachments;
  }

  public void setAttachments(Action attachments) {
    this.attachments = attachments;
  }

  public CandidateDetailsActions consent(Action consent) {
    this.consent = consent;
    return this;
  }

   /**
   * Get consent
   * @return consent
  **/
  @Schema(description = "")
  public Action getConsent() {
    return consent;
  }

  public void setConsent(Action consent) {
    this.consent = consent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidateDetailsActions candidateDetailsActions = (CandidateDetailsActions) o;
    return Objects.equals(this.properties, candidateDetailsActions.properties) &&
        Objects.equals(this.attachments, candidateDetailsActions.attachments) &&
        Objects.equals(this.consent, candidateDetailsActions.consent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(properties, attachments, consent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidateDetailsActions {\n");
    
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    consent: ").append(toIndentedString(consent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
