/*
 * Candidates API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.smartrecruiters.api.candidates.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CandidateStatusEnum
 */
@JsonAdapter(CandidateStatusEnum.Adapter.class)
public enum CandidateStatusEnum {
  LEAD("LEAD"),
  NEW("NEW"),
  IN_REVIEW("IN_REVIEW"),
  INTERVIEW("INTERVIEW"),
  OFFERED("OFFERED"),
  HIRED("HIRED"),
  REJECTED("REJECTED"),
  WITHDRAWN("WITHDRAWN"),
  TRANSFERRED("TRANSFERRED");

  private String value;

  CandidateStatusEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CandidateStatusEnum fromValue(String text) {
    for (CandidateStatusEnum b : CandidateStatusEnum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CandidateStatusEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final CandidateStatusEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CandidateStatusEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CandidateStatusEnum.fromValue(String.valueOf(value));
    }
  }
}
