/*
 * Candidates API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.smartrecruiters.api.candidates.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.candidates.model.Action;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * JobJobActions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-29T00:16:14.530797+01:00[Europe/London]")
public class JobJobActions {
  @SerializedName("details")
  private Action details = null;

  @SerializedName("positionDetails")
  private Action positionDetails = null;

  public JobJobActions details(Action details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @Schema(required = true, description = "")
  public Action getDetails() {
    return details;
  }

  public void setDetails(Action details) {
    this.details = details;
  }

  public JobJobActions positionDetails(Action positionDetails) {
    this.positionDetails = positionDetails;
    return this;
  }

   /**
   * Get positionDetails
   * @return positionDetails
  **/
  @Schema(description = "")
  public Action getPositionDetails() {
    return positionDetails;
  }

  public void setPositionDetails(Action positionDetails) {
    this.positionDetails = positionDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobJobActions jobJobActions = (JobJobActions) o;
    return Objects.equals(this.details, jobJobActions.details) &&
        Objects.equals(this.positionDetails, jobJobActions.positionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, positionDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobJobActions {\n");
    
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    positionDetails: ").append(toIndentedString(positionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
